from __future__ import annotations

import base64
import gc
import os
import threading
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import yt_dlp

YOUTUBE_STREAM_HEADERS = {
    "Referer": "https://www.youtube.com/",
    "Origin": "https://www.youtube.com",
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/131.0.0.0 Safari/537.36"
    ),
}

# Prefer clients that work with cookies + EJS challenge solving.
YOUTUBE_PLAYER_CLIENTS_WITH_COOKIES: list[list[str]] = [
    ["web", "mweb"],
    ["tv_embedded"],
    ["web_safari"],
    ["web"],
]

YOUTUBE_PLAYER_CLIENTS_WITHOUT_COOKIES: list[list[str]] = [
    ["android_vr"],
    ["tv_embedded"],
    ["web_safari"],
    ["ios", "web"],
    ["android", "web"],
]


_YTDLP_LOCK = threading.Lock()
_DEFAULT_STREAM_CLIENT_ATTEMPTS = 2
_DEFAULT_METADATA_CLIENT_ATTEMPTS = 2
_DEFAULT_SEARCH_CLIENT_ATTEMPTS = 1


@contextmanager
def _serialized_ytdlp():
    """One yt-dlp job at a time — avoids OOM on 512MB hosts (Render free tier)."""
    with _YTDLP_LOCK:
        try:
            yield
        finally:
            gc.collect()


def _player_client_attempts(limit: int | None = None) -> list[list[str]]:
    if _resolve_cookie_file():
        attempts = (
            YOUTUBE_PLAYER_CLIENTS_WITH_COOKIES + YOUTUBE_PLAYER_CLIENTS_WITHOUT_COOKIES
        )
    else:
        attempts = (
            YOUTUBE_PLAYER_CLIENTS_WITHOUT_COOKIES + YOUTUBE_PLAYER_CLIENTS_WITH_COOKIES
        )

    if limit is not None:
        return attempts[:limit]
    return attempts


def _utc_iso(offset_seconds: int = 3600) -> str:
    instant = datetime.now(timezone.utc) + timedelta(seconds=offset_seconds)
    return instant.replace(microsecond=0).isoformat().replace("+00:00", "Z")


_resolved_cookie_file: str | None = None

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.haxx.se/rfc/cookie_spec.html\n"
    "# This file was generated by OneTune. Do not edit.\n\n"
)


def _is_cookie_line(line: str) -> bool:
    stripped = line.strip()
    return bool(stripped) and not stripped.startswith("#") and "\t" in stripped


def _normalize_cookie_content(raw: str) -> str:
    text = raw.replace("\r\n", "\n").replace("\r", "\n").strip()
    if not text:
        raise ValueError("Cookie content is empty")

    cookie_lines = [line.strip() for line in text.split("\n") if _is_cookie_line(line)]
    if not cookie_lines:
        raise ValueError("Cookie content has no Netscape cookie rows")

    return NETSCAPE_HEADER + "\n".join(cookie_lines) + "\n"


def _decode_cookie_env_value(value: str) -> str:
    trimmed = value.strip()
    if not trimmed:
        raise ValueError("Cookie env value is empty")

    if trimmed.startswith("# Netscape") or _is_cookie_line(trimmed):
        return _normalize_cookie_content(trimmed)

    cleaned = "".join(trimmed.split())
    padding = (-len(cleaned)) % 4
    cleaned += "=" * padding

    try:
        decoded = base64.b64decode(cleaned, validate=False)
    except Exception as exc:  # noqa: BLE001
        raise ValueError("YTDLP_COOKIES_BASE64 is not valid base64") from exc

    try:
        text = decoded.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError("Decoded cookies are not valid UTF-8 text") from exc

    return _normalize_cookie_content(text)


def _resolve_cookie_file() -> str | None:
    """Resolve cookie file from disk path or YTDLP_COOKIES_BASE64 (for Render / PaaS)."""
    global _resolved_cookie_file

    if _resolved_cookie_file and Path(_resolved_cookie_file).is_file():
        return _resolved_cookie_file

    cookie_file = os.environ.get("YTDLP_COOKIE_FILE", "").strip()
    if cookie_file and Path(cookie_file).is_file():
        existing = Path(cookie_file).read_text(encoding="utf-8")
        normalized = _normalize_cookie_content(existing)
        if normalized != existing:
            Path(cookie_file).write_text(normalized, encoding="utf-8", newline="\n")
        _resolved_cookie_file = cookie_file
        return cookie_file

    encoded = os.environ.get("YTDLP_COOKIES_BASE64", "").strip()
    if not encoded:
        return None

    target = os.environ.get("YTDLP_COOKIE_FILE", "").strip() or "/tmp/youtube-cookies.txt"
    normalized = _decode_cookie_env_value(encoded)
    Path(target).write_text(normalized, encoding="utf-8", newline="\n")
    _resolved_cookie_file = target
    return target


def _auth_opts() -> dict[str, Any]:
    opts: dict[str, Any] = {}

    cookie_file = _resolve_cookie_file()
    if cookie_file:
        opts["cookiefile"] = cookie_file

    browser = os.environ.get("YTDLP_COOKIES_FROM_BROWSER", "").strip()
    if browser and "cookiefile" not in opts:
        opts["cookiesfrombrowser"] = (browser,)

    return opts


def _youtube_extractor_args(player_clients: list[str]) -> dict[str, Any]:
    youtube_args: dict[str, list[str]] = {"player_client": player_clients}

    po_token = os.environ.get("YTDLP_PO_TOKEN", "").strip()
    if po_token:
        youtube_args["po_token"] = [po_token]

    visitor_data = os.environ.get("YTDLP_VISITOR_DATA", "").strip()
    if visitor_data:
        youtube_args["visitor_data"] = [visitor_data]

    return {"youtube": youtube_args}


def _base_opts(**extra: Any) -> dict[str, Any]:
    return {
        "quiet": True,
        "no_warnings": True,
        "skip_download": True,
        "nocheckcertificate": True,
        "remote_components": ["ejs:github"],
        "js_runtimes": {"deno": {}},
        **_auth_opts(),
        **extra,
    }


def _youtube_opts(player_clients: list[str], **extra: Any) -> dict[str, Any]:
    return _base_opts(
        extractor_args=_youtube_extractor_args(player_clients),
        **extra,
    )


def _stream_youtube_opts(player_clients: list[str]) -> dict[str, Any]:
    return _youtube_opts(
        player_clients,
        ignore_no_formats_error=True,
    )


def _youtube_thumbnail_url(video_id: str) -> str:
    return f"https://i.ytimg.com/vi/{video_id}/hqdefault.jpg"


def _parse_artist_from_title(title: str) -> str | None:
    for sep in (" - ", " – ", " — ", " | ", ": "):
        if sep in title:
            artist = title.split(sep, 1)[0].strip()
            if artist and len(artist) <= 80:
                return artist
    return None


def _pick_thumbnail(info: dict[str, Any], video_id: str | None = None) -> str | None:
    thumb = info.get("thumbnail")
    if thumb:
        return str(thumb)

    thumbnails = info.get("thumbnails")
    if isinstance(thumbnails, list):
        valid = [
            item
            for item in thumbnails
            if isinstance(item, dict) and item.get("url")
        ]
        if valid:
            best = max(valid, key=lambda item: int(item.get("height") or 0))
            return str(best["url"])

    vid = video_id or info.get("id")
    if vid:
        return _youtube_thumbnail_url(str(vid))
    return None


def _map_artists(info: dict[str, Any]) -> list[dict[str, str | None]]:
    for key in ("artist", "creator", "uploader", "channel", "album_artist"):
        value = info.get(key)
        if value:
            name = str(value).strip()
            if name and name.lower() not in {"unknown", "n/a"}:
                channel_id = info.get("channel_id") or info.get("uploader_id")
                return [
                    {
                        "id": str(channel_id) if channel_id else None,
                        "name": name,
                    }
                ]

    title = info.get("title") or ""
    parsed = _parse_artist_from_title(title)
    if parsed:
        return [{"id": None, "name": parsed}]

    return [{"id": None, "name": "Unknown Artist"}]


def _map_flat_entry(entry: dict[str, Any]) -> dict[str, Any]:
    entry_id = entry.get("id") or ""
    duration = entry.get("duration")

    return {
        "id": entry_id,
        "provider": "youtube",
        "title": entry.get("title") or "Unknown Title",
        "artists": _map_artists(entry),
        "album": None,
        "artwork_url": _pick_thumbnail(entry, entry_id or None),
        "duration_ms": int(duration * 1000) if duration else None,
        "is_video": entry.get("vcodec") not in (None, "none"),
        "url": entry.get("url") or f"https://www.youtube.com/watch?v={entry_id}",
    }


def _map_track(info: dict[str, Any]) -> dict[str, Any]:
    video_id = info.get("id") or ""
    webpage_url = info.get("webpage_url") or info.get("original_url") or ""
    duration = info.get("duration")

    return {
        "id": video_id,
        "provider": "youtube",
        "title": info.get("title") or "Unknown Title",
        "artists": _map_artists(info),
        "album": None,
        "artwork_url": _pick_thumbnail(info, video_id or None),
        "duration_ms": int(duration * 1000) if duration else None,
        "is_video": info.get("vcodec") not in (None, "none"),
        "url": webpage_url,
    }


def _is_progressive_format(fmt: dict[str, Any]) -> bool:
    protocol = str(fmt.get("protocol") or "")
    return "m3u8" not in protocol and "dash" not in protocol


def _format_sort_key(fmt: dict[str, Any], prefer_video: bool) -> tuple[int, int, int, int]:
    has_audio = fmt.get("acodec") not in (None, "none")
    has_video = fmt.get("vcodec") not in (None, "none")
    abr = int(fmt.get("abr") or 0)
    height = int(fmt.get("height") or 0)
    progressive = 1 if _is_progressive_format(fmt) else 0

    if prefer_video:
        return (
            1 if has_video else 0,
            progressive,
            height,
            abr,
        )

    audio_only = 1 if has_audio and not has_video else 0
    audio_with_video = 1 if has_audio and has_video else 0
    return (audio_only, progressive, abr, audio_with_video * height)


def _stream_format_selector(prefer_video: bool) -> list[str]:
    if prefer_video:
        return [
            "bestvideo[height<=720]+bestaudio/best[height<=720]/best",
            "best[height<=720]/best",
        ]

    return [
        "bestaudio[ext=m4a]/bestaudio[ext=webm]/bestaudio",
        "best[acodec!=none][vcodec=none]/best[acodec!=none]",
        "bestaudio/best",
    ]


def _format_with_url(fmt: dict[str, Any]) -> dict[str, Any] | None:
    if fmt.get("url"):
        return fmt
    if fmt.get("manifest_url"):
        return {**fmt, "url": fmt["manifest_url"]}
    if fmt.get("fragment_base_url"):
        return {**fmt, "url": fmt["fragment_base_url"]}
    return None


def _format_from_info(info: dict[str, Any], prefer_video: bool = False) -> dict[str, Any] | None:
    if info.get("url"):
        return {
            "url": info["url"],
            "ext": info.get("ext"),
            "abr": info.get("abr") or info.get("tbr"),
            "vcodec": info.get("vcodec"),
            "mime_type": info.get("mime_type"),
        }

    requested = info.get("requested_formats") or []
    resolved = [
        picked
        for fmt in requested
        if (picked := _format_with_url(fmt)) is not None
    ]
    if resolved:
        return max(
            resolved,
            key=lambda fmt: _format_sort_key(fmt, prefer_video=prefer_video),
        )

    return _pick_format(info, prefer_video=prefer_video)


def _pick_format(info: dict[str, Any], prefer_video: bool = False) -> dict[str, Any] | None:
    formats = info.get("formats") or []
    candidates = [
        picked
        for fmt in formats
        if (picked := _format_with_url(fmt)) is not None
    ]

    if not candidates and info.get("url"):
        return {
            "url": info["url"],
            "ext": info.get("ext"),
            "abr": info.get("abr") or info.get("tbr"),
            "vcodec": info.get("vcodec"),
            "mime_type": info.get("mime_type"),
        }

    if not candidates:
        return None

    return max(
        candidates,
        key=lambda fmt: _format_sort_key(fmt, prefer_video=prefer_video),
    )


def _extract_info(
    url: str,
    player_clients: list[str],
    *,
    for_stream: bool = False,
    format_selector: str | None = None,
) -> dict[str, Any]:
    extra: dict[str, Any] = {}
    if format_selector:
        extra["format"] = format_selector

    opts = (
        _stream_youtube_opts(player_clients)
        if for_stream and not format_selector
        else _youtube_opts(player_clients, **extra)
    )
    if for_stream and format_selector:
        opts = _stream_youtube_opts(player_clients)
        opts["format"] = format_selector

    with yt_dlp.YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=False)
        if info.get("_type") == "playlist":
            raise ValueError("URL is a playlist — use playlist import endpoint")
        return info


def _build_stream_payload(chosen: dict[str, Any]) -> dict[str, Any]:
    is_video = chosen.get("vcodec") not in (None, "none")
    abr = chosen.get("abr")
    ext = chosen.get("ext")
    mime_type = chosen.get("mime_type")
    if not mime_type and ext:
        mime_type = {
            "m4a": "audio/mp4",
            "mp4": "video/mp4",
            "webm": "audio/webm",
            "opus": "audio/opus",
            "m3u8": "application/vnd.apple.mpegurl",
            "mpd": "application/dash+xml",
        }.get(str(ext))

    return {
        "url": chosen["url"],
        "expires_at": _utc_iso(3600),
        "mime_type": mime_type,
        "bitrate": int(abr * 1000) if abr else None,
        "is_video": is_video,
        "headers": dict(YOUTUBE_STREAM_HEADERS),
    }


def extract_metadata(url: str) -> dict[str, Any]:
    last_error: Exception | None = None
    with _serialized_ytdlp():
        for clients in _player_client_attempts(limit=_DEFAULT_METADATA_CLIENT_ATTEMPTS):
            try:
                return _map_track(_extract_info(url, clients))
            except Exception as exc:  # noqa: BLE001
                last_error = exc

    raise ValueError(str(last_error) if last_error else "Could not extract metadata")


def search_tracks(query: str, limit: int) -> list[dict[str, Any]]:
    search_url = f"ytsearch{limit}:{query}"
    last_error: Exception | None = None

    with _serialized_ytdlp():
        for clients in _player_client_attempts(limit=_DEFAULT_SEARCH_CLIENT_ATTEMPTS):
            try:
                with yt_dlp.YoutubeDL(_youtube_opts(clients, extract_flat=True)) as ydl:
                    info = ydl.extract_info(search_url, download=False)
                break
            except Exception as exc:  # noqa: BLE001
                last_error = exc
        else:
            raise ValueError(str(last_error) if last_error else "Search failed")

    entries = info.get("entries") or []
    results: list[dict[str, Any]] = []

    for entry in entries:
        if not entry:
            continue
        entry_id = entry.get("id")
        if not entry_id:
            continue
        results.append(_map_flat_entry(entry))

    return results


def resolve_stream(url: str, prefer_video: bool = False) -> dict[str, Any]:
    last_error: Exception | None = None
    format_selectors = _stream_format_selector(prefer_video)[:2]

    with _serialized_ytdlp():
        for clients in _player_client_attempts(limit=_DEFAULT_STREAM_CLIENT_ATTEMPTS):
            try:
                info = _extract_info(url, clients, for_stream=True)
                chosen = _format_from_info(info, prefer_video=prefer_video)
                if chosen and chosen.get("url"):
                    return _build_stream_payload(chosen)
            except Exception as exc:  # noqa: BLE001
                last_error = exc

            for format_selector in format_selectors:
                try:
                    info = _extract_info(
                        url,
                        clients,
                        for_stream=True,
                        format_selector=format_selector,
                    )
                    chosen = _format_from_info(info, prefer_video=prefer_video)
                    if chosen and chosen.get("url"):
                        return _build_stream_payload(chosen)
                except Exception as exc:  # noqa: BLE001
                    last_error = exc

    raise ValueError(str(last_error) if last_error else "No playable stream URL found")


def resolve_download(url: str) -> dict[str, Any]:
    with _serialized_ytdlp():
        info = _extract_info(
            url,
            _player_client_attempts(limit=1)[0],
            for_stream=True,
        )
        chosen = _pick_format(info, prefer_video=False)
        if not chosen or not chosen.get("url"):
            raise ValueError("No downloadable URL found")

        title = info.get("title") or "track"
        ext = chosen.get("ext") or "m4a"
        safe_title = "".join(c if c.isalnum() or c in "- _" else "_" for c in title)

        return {
            "url": chosen["url"],
            "filename": f"{safe_title}.{ext}",
            "format": ext,
            "size_bytes": chosen.get("filesize") or chosen.get("filesize_approx"),
            "expires_at": _utc_iso(3600),
        }


def import_playlist(url: str, max_tracks: int = 100) -> dict[str, Any]:
    with _serialized_ytdlp():
        opts = _youtube_opts(_player_client_attempts(limit=1)[0], extract_flat=True)

        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=False)

        if info.get("_type") != "playlist":
            raise ValueError("URL is not a playlist")

        entries = (info.get("entries") or [])[:max_tracks]
        tracks: list[dict[str, Any]] = []

        for entry in entries:
            if not entry:
                continue
            entry_id = entry.get("id")
            if not entry_id:
                continue
            tracks.append(_map_flat_entry(entry))

        return {
            "id": info.get("id"),
            "name": info.get("title") or "Imported Playlist",
            "description": info.get("description"),
            "artwork_url": _pick_thumbnail(info),
            "track_count": len(tracks),
            "owner": info.get("uploader"),
            "source_url": url,
            "tracks": tracks,
        }


def build_youtube_url(external_id: str, url: str | None = None) -> str:
    if url:
        return url
    if external_id.startswith("http"):
        return external_id
    return f"https://www.youtube.com/watch?v={external_id}"
